version: "3"
services:
  # The nginx reverse proxy.
  # used for reverse proxying the API service and Web service.
  nginx_proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy.conf:/etc/nginx/proxy.conf
      - ./conf.d:/etc/nginx/conf.d
      #- ./nginx/ssl:/etc/ssl
    ports:
      - "80:80"
      #- "443:443"
    networks:
      - superbot_default

networks:
  superbot_default:
    name: superbot_default
    external: true